# The Firebase tools want a v6.x version of Node but Circle CI
# defaults to v4.x. Set the latest LTS version.
#

version: 2

jobs:
    build-and-deploy:
          docker:
            - image: starefossen/ruby-node:2-8

          working_directory: ~/repo

          steps:
              - checkout
              - restore_cache:
                  keys:
                    - v2-dependencies-{{ checksum "Gemfile.lock" }}
                    - v2-dependencies-
              - run:
                  name: Bundle Install
                  command: bundle check || bundle install
              - save_cache:
                  key: v2-dependencies-{{ checksum "Gemfile.lock" }}
                  paths:
                    - /usr/local/bundle
                    - /usr/local/lib/node_modules
              - run:
                  name: Jekyll Build
                  command: JEKYLL_ENV=production bundle exec jekyll build --verbose
              - persist_to_workspace:
                  root: ./
                  paths:
                    - _site
              - run:
                  name: Deploy
                  command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --non-interactive
# How you tell Circle to deploy to Firebase. The important thing to
# note here is the FIREBASE_TOKEN env variable. See below.
    # deploy:
    #       docker:
    #         - image: circleci/node:7.10-browsers
    #       steps:
    #         - run:
    #             name: npm Install
    #             command: npm install -g firebase-tools@3.19.3 --unsafe-perm
    #         - run:
    #             name: Deploy Master to Firebase
    #             command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
    version: 2
    -deploy:
      jobs:
        - build-and-deploy
      filters:
        branches:
          only: develop
